#pragma once

#define KEY_TOP 165
#define KEY_LEFT 80

#define KEY_LEFT_OFFSET 5
#define KEY_TOP_OFFSET 5
#define KEY_BUTTON_SIZE 30

#define KEY_Y1_1 KEY_TOP + KEY_TOP_OFFSET
#define KEY_Y2_1 KEY_TOP + KEY_TOP_OFFSET + KEY_BUTTON_SIZE

#define KEY_Y1_2 KEY_TOP + 2*KEY_TOP_OFFSET + KEY_BUTTON_SIZE
#define KEY_Y2_2 KEY_TOP + 2*KEY_TOP_OFFSET + 2*KEY_BUTTON_SIZE

#define KEY_X1 KEY_LEFT + ( i * ( KEY_BUTTON_SIZE + KEY_LEFT_OFFSET ))		
#define KEY_X2 KEY_LEFT + ( i * ( KEY_BUTTON_SIZE + KEY_LEFT_OFFSET ) ) + KEY_BUTTON_SIZE		

